### ISSUE TITLE
VerticalViewPager on TwoPage Sample Unresponsive

### ISSUE THREAD

**Issue by YasserDbeis** [microsoft/surface-duo-sdk-samples-kotlin#50]
All horizontal swiping is fine for the TwoPage sample, but when in the dual landscape screen configuration, the vertical scrolling can miss some of the swiping events and is overall not as smooth as swiping through pages horizontally. This bug is shown in the demonstration [here](https://www.youtube.com/watch?v=UM8Q_IdVzTE&ab_channel=YasserDbeis).

This problem is apparently amplified (vertical scrolling is even less responsive) when using Jetpack Window Manager instead of the Surface Duo SDK to manage the layout. This is not confirmed, but in my app's case, the only real difference was that it used JWM instead of the Duo SDK and only the vertical scroll seemed to perform worse. 

To reproduce, simply enter the dual landscape screen configuration and swipe up and down through the pages. The issue is independent of any prior configurations, as I was able to reproduce it starting from every configuration/orientation before switching to dual landscape. I even tried going straight to dual landscape and the problem still occurred.

**Comment by CesarValiente** [comment]
@soalb-m @ancirja-m please, whenever you have time have a look to the issue Yasser has just sent.
The link to the repro video is [here](https://www.youtube.com/watch?v=UM8Q_IdVzTE)  (the link in the description is not well formed).

**Comment by soalb-m** [comment]
Thank you Yasser for reporting this.

We managed to replicate the issues and it will be fixed in the following days.

**Comment by soalb-m** [comment]
Hi,

As of today, the issue should be fixed.

Thanks!
